### ISSUE TITLE
Demo page 404

### ISSUE THREAD

**Issue by micc83** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#183]
Hi, the demo page is not working anymore.

**Comment by stojankukrika** [comment]
Yes. I delete it today, because some user is put virus code which is stop work server which I use to hosting and I need do delete it. Host owner, hostgator users, tell me that I have some virus code on my start site(someone is upload some virus code on server) and I need to delete it or they delete it. So I must delete it. Sorry.
